version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns:
          - react*
          - vite*
          - "@vitejs/*"
          - tailwindcss
          - "@tailwindcss/*"
      tauri-js:
        patterns:
          - "@tauri-apps/*"
      whatsapp:
        patterns:
          - whatsapp-web.js

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    groups:
      tauri-rust:
        patterns:
          - tauri*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
